version: '3.8'

services:
  stub-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RESPONSE_DIR=./responses
      - DEFAULT_RESPONSE=default.json
      - LOOKUP_FIELD=id
      - LOG_LEVEL=info
    volumes:
      - ./responses:/app/responses
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

